import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const css = await readFile(resolve(root, 'src/client/deep-whale.module.css'), 'utf8')
const runtime = (await readFile(resolve(root, 'src/client/runtime.js'), 'utf8'))
  .replace('export function apply(ctx)', 'function apply(ctx)')
const assetFiles = {
  backgroundDay: '01-background-day.webp',
  backgroundNight: '02-background-night.webp',
  heroGirlWhale: '03-hero-girl-whale.webp',
  topCurrent: '06-top-current.webp',
  heroSeafloor: '07-hero-seafloor.webp',
  composerSeafloor: '08-composer-seafloor.webp',
  detailsCorner: '09-details-corner.webp',
  newSessionFrame: '10-new-session-frame.webp',
  settingsFrame: '11-settings-frame.webp',
  workspaceRibbon: '12-workspace-ribbon.webp',
  brandWhale: '13-brand-whale.webp',
  detailsGirl: '14-details-girl.webp',
  statusWhale: '15-status-whale.webp',
}
const assets = Object.fromEntries(await Promise.all(Object.entries(assetFiles).map(async ([name, file]) => {
  const data = await readFile(resolve(root, 'assets/deep-whale', file))
  return [name, `data:image/webp;base64,${data.toString('base64')}`]
})))
const installCss = `function installCss(){ const id='@nishuobushuo/dsh-client-ui-skin-deep-whale/deep-whale.module.css'; if(document.querySelector('style[data-plugin-css="'+id+'"]')) return; const tag=document.createElement('style'); tag.dataset.pluginCss=id; tag.textContent=css; document.head.append(tag); }\n`
const moduleId = '@nishuobushuo/dsh-client-ui-skin-deep-whale'
const client = `// Generated by scripts/build.mjs; source lives in src/client/.\nwindow.__ModuleLoader__.load({\n  id: ${JSON.stringify(moduleId)},\n  factory: (require) => {\n    const module = { exports: {} };\n    const exports = module.exports;\n    const css = ${JSON.stringify(css)};\n    const assets = Object.freeze(${JSON.stringify(assets)});\n    ${installCss}\n    ${runtime}\n    exports.apply = apply;\n    return module.exports;\n  }\n});\n`
await mkdir(resolve(root, 'lib'), { recursive: true })
await writeFile(resolve(root, 'lib/index.js'), '/** Host loader: browser-only skin. */\nexport function apply() {}\n')
await writeFile(resolve(root, 'lib/client.js'), client)
